[package]
name = "recapn"
version = "0.1.0"
authors = ["Sydney Acksman <obsidianminor@gmail.com>"]
edition = "2021"

[features]
default = ["std"]
alloc = []
std = ["alloc"]

[lints]
workspace = true

